services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    networks:
      - ctf-net
    depends_on:
      - internal-api

  internal-api:
    build: ./internal-api
    networks:
      - ctf-net
    environment:
      - "CTF_FLAG=LUN4R{SSRF_le4ds_t0_id0r_1nternal_p1v0t}"

networks:
  ctf-net:
    driver: bridge